language: node_js
node_js:
- 5.0.0
env:
  global:
  #- secure: fwJrSL0emaIKUtKrS89oMn94bRKqR/YYGT18ycYp94Z88nryJdfBexuPRJpz8z+hyco3NgcgxEjT4Wz5skY0OTJcH4jwAqOXv22R4kpAwqUmBp+qcxahfbc01VANuYrsRG5hS6InkfuqeInaEmmUwn1I7Ht8zU+lP+oSzBVyKGyZfWNbq8SJu2Tr60HgocO46Ui0jLyu3F3NVIzBvm8V+MhXFZFA/Ay3rHu9+t28ruhIrhGoIUUI9YYvFy2JkU+K4+ckARg3bG/UPTb0mEs0vO+UM/rTwgjYOH0tioAuwY/BI1OYQqlKAcgI+HDWw/syEdUtTT8nw4MkGNjznhNNCQC8zEgmKflvsrhY5qB652dQ5nuVBM/dzNzersSc5NXb8V2td7z9A0zlJ2XFze066i73QYPrXLEGj62guq8PND6PFrtuvZG5hAMtl1UmQe/RXPhRBGqnOCrp2P5fGOqjD5eWgVU+FPladlOEkimen35iTDRwrSkh3FesYd2i8j4V0Tz3yry9VHXTdwcg9MAbqFyqMah2X5ptroYZmqFh/zl/kRY+AcKfDJ3QdLqoWK10M/nBJ/iE/MGPItA2wRO8cuD8ew4eRtvQLoyFvSivYv3SFd8nZMvKhRhY9XjlXXEEEUcZnXMSGcBtDxiIK24ldXxWRtlafRZJ2Z0p3E+eeHU=
  - secure: j+VgYPRO1tvClBO7slSuAT1iuQgysv9m4ytGa2yzdCVUGzSaGNE2fn5ZLx6QHGeiafe931SVTIW3rxIvFUYKjqEEe+aj1kBQYdwLWgHdaAk0ifZWSxO5AOj6G5LEz/RnRrKg8ZnrbipXMQa+V73+y1TDBk5X6YwTMMiPNYKgtwOvRjjrkRBCpwM/OqOII+V3vGIACEDKLQHRHLoND16Ab6B+KlAcQSuoqsDNihOHYsRmUvtERRBhYBmz2byzCaET+Um7xRwNZ84qFGhcaAZBo6VHSpl1uI/LvGoAt6O0ETsU/OxMBg7o7/9zw5Wyg93HRzMfZXSDaDB9qTbkJvWTsLyDUUmw0+u5/v04ZzBqRUg+NCrBPLGSB3jI4QxN6ssxocKJ8VI1GP8HdO5Q6lWtrIeACF3gaNkjxoaY+s+PbBdZyHixkzKFfrl81V/053kzYynVz9sNDv9KFqAw29tyZYM6jAHlk+r81uZBnT5wj+HX3vZhDCEcmdVWKChADAIIgnifAgYP8cCjkL7ch3EehcJDb4rVbsuOdd8xiZExFQW43Xu+j2tNz3fCSUtd+xCvlzf5TEbvkxRW/9XGkbYsZDrCUiwFA8MEK9kSYXJfExCZvnPJ5161f+FUP3pP3/LANBVD8CVKdP3q5gKMhgi+maFG7G8VKHpej1KLEYCsoak=
before_script: 
before_install:
- npm install jspm -g
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
install:
- npm install
- jspm install -y
script: 
deploy:
  provider: heruko
  api_key: "$HERUKO_API_KEY"
  app: digitaler-kleiderschrank
